config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :ideas
  root "ideas#index"
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :ideas
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :find_idea, only: [:show,:edit,:update,:destroy]
  before_action :authenticate_user!, except: [:index,:show]
    def index
      @idea=Idea.all.order("created_at DESC")
    end
    def new
      @idea=current_user.ideas.build()
    end
    def create
      @idea=current_user.ideas.build(find_params)

      if(@idea.save)
        redirect_to @idea,notice: "Successfully Broadcasted new Idea"
      else
        render 'new'
      end
    end
    def show

    end
    def edit
        if current_user!=@idea.user
          redirect_to :root
        end
    end
    def update
      if @idea.update(find_params)
        redirect_to @idea, notice: "Idea was Successfully updated!"
      else
        render 'edit'
      end
    end
    def destroy
      @idea.destroy
      redirect_to root_path
    end

    private

    def find_params
      params.require(:idea).permit(:title,:description,:image)
    end

    def find_idea
      @idea=Idea.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.haml
= simple_form_for @idea ,{multipart: true} do |f|
    -if @idea.errors.any?
        #errors
        %h2
        =pluralize(@idea.errors.count, "error")
        prevented this idea from saving
        %ul
        -@idea.errors.full_messages.each do |msg|
            %li =msg
    .form_group
    =f.input :image
    .form_group
    =f.input :title, input_html: { class: 'form-control'}
    .form_group
    =f.input :description, input_html: { class: 'form-control'}
    = f.button :submit, class: "btn btn-primary"

app/views/ideas/edit.html.haml
.col-md-6.col-md-offset-3
  %h1 Edit Page
  =image_tag @idea.image.url(:medium)
  =render 'form'
  =link_to "cancel",idea_path
  |
  =link_to "Delete",idea_path,method: :delete,data: {confirm: "Are you sure?" }

app/views/ideas/index.html.haml
#ideas.transition-enabled
  -@idea.each do |idea|
    .box.panel.panel-default
      =link_to (image_tag idea.image.url),idea
      .panel-body
        %h2=link_to idea.title, idea
        %p.user
          Subitted by
          =idea.user.email

app/views/ideas/new.html.haml
.col-md-6.col-md-offset-3
  %h1 New Post
  = render 'form'
  =link_to "back", root_path

app/views/ideas/show.html.haml
#idea_show.row
  .col-md-8.col-md-offet-2
    .panel.panel-default
      .panel-heading.idea_image
        =image_tag @idea.image.url(:medium)
      .panel-body
        %h1= @idea.title
        %p.description=@idea.description
        %p
        Submitted by
        =@idea.user.email
      .panel-footer
        .row
          .col-md-6
            %p.user
            Submitted by
            = @idea.user.email
          .col-md-6
            .btn-group.pull-right
              -if current_user==@idea.user
                =link_to "Edit", edit_idea_path,class: "btn btn-default"

app/views/layouts/application.html.haml
!!!5
%html
%head
  %title Quirkyeye
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
  %style
    @import url('https://fonts.googleapis.com/css?family=Gloria+Hallelujah|Pacifico');
%body
  %nav.navbar.navbar-default
    .container
      .navbar-brand#logo=link_to "QuirkyEye",root_path

      -if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li=link_to "New Idea",new_idea_path
          %li=link_to "Account",edit_user_registration_path
          %li=link_to "Sign Out",destroy_user_session_path,method: :delete
      -else
        %ul.nav.navbar-nav.navbar-right
          %li=link_to "Sign Up",new_user_registration_path
          %li=link_to "Sign In ",new_user_session_path
  .container.page
    - flash.each do|name,msg|
      =content_tag :div,msg,class: "alert alert-info"
    =yield